
# fly.toml app configuration file generated for mndiscordbot on 2025-07-28T21:34:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mndiscordbot'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

